added solution hb-01
IgorBochkor/hibernate-cinema pull request #1
Opened 2021-01-26 15:07 UTC by IgorBochkor

added solution hb-01

2021-01-26 16:20 UTC, Baldinini requested changes

2021-01-26 16:20 UTC, Baldinini commented on pom.xml
> +        </dependency>
не уверенна по поводу этой зависимости, нужна ли она вообще

2021-01-26 16:20 UTC, Baldinini commented on pom.xml
>  </project>
добавь пустую строку

2021-01-26 16:20 UTC, Baldinini commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
тоже самое

2021-01-26 17:07 UTC, Baldinini commented on src/main/java/com/dev/cinema/dao/MovieDaoImpl.java
> +            throw new DataProcessingException("Can't insert movie entity", e);
```suggestion
            throw new DataProcessingException("Can't insert movie entity" + movie, e);
```

2021-01-26 18:38 UTC, IgorBochkor commented on pom.xml
> +        </dependency>
Побачив цю залежність у відео. Перевір, без неї також все працює. Видалив

2021-01-26 18:39 UTC, IgorBochkor commented on pom.xml
>  </project>
добавив

2021-01-26 18:39 UTC, IgorBochkor commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
добавив

2021-01-26 18:39 UTC, IgorBochkor commented on src/main/java/com/dev/cinema/dao/MovieDaoImpl.java
> +            throw new DataProcessingException("Can't insert movie entity", e);
добавив

2021-01-26 18:46 UTC, Baldinini approved these changes

2021-01-27 08:06 UTC, Sofasmile requested changes

2021-01-27 08:06 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/MovieDaoImpl.java
> +            movie.setId(itemId);
https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_01.html

2021-01-27 10:03 UTC, RomanDubovskyi approved these changes

2021-01-28 09:33 UTC, merged